version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env.test
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./db/migrations/20250414161816_initial.sql:/docker-entrypoint-initdb.d/20250414161816_initial.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_test"]
      interval: 5s
      timeout: 5s
      retries: 5